Cleaning + adding new example
oalders/github-mergevelocity pull request #5
Opened 2022-05-07 13:58 UTC by thibaultduponchelle

A new example if we only want to get the velocity without report.

2022-05-07 20:50 UTC, oalders requested changes
Great idea to add this example. Just had one suggestion.

2022-05-07 20:50 UTC, oalders commented on examples/print-repository-velocity.pl
> +my @repos = map { $mv->_repository_for_url($_) } $mv->_report_urls;
We should probably make `_repository_for_url` and `_report_urls` public if we're going to do this. I try to make the majority of the API private by default unless there's a reason for it to be public. Doing the above demonstrates that those methods should probably be public.

2022-08-21 15:13 UTC, closed without merging

2022-08-22 02:44 UTC, oalders commented
@thibaultduponchelle did you intend to close this?

2022-08-22 07:21 UTC, thibaultduponchelle commented
Hi @oalders 

Hmm I thought deleting the fork would not close the PR... Actually it's not that bad as I'm probably not going to work on the remaining changes anytime soon.